### ISSUE TITLE
歌单列表都不能上下滚动

### ISSUE THREAD

**Issue by Reset0921** [fujiazhang/Music-For-The-Poor#1]
歌单列表都不能上下滚动

**Comment by fujiazhang** [comment]
在pc谷歌浏览器下初始化打开，开启手机调试模式后，需要刷新一次，better-scroll才会初始化噢。
我这边没有这个问题噢，如果还有麻烦截图题issue ，我好修复，嘿嘿

**Comment by DullSword** [comment]
感觉目前的操作方式更适合移动端，PC浏览器上我还是更习惯用滚轮上下移动。
