### ISSUE TITLE
如何自己部署后端api?

### ISSUE THREAD

**Issue by karma-sun** [fujiazhang/Music-For-The-Poor#28]
如何自己部署后端api?
没有找到后端的代码

**Comment by 0xA1b** [comment]
抱歉才看到，关羽接口文档，你可以参考[这里](https://jsososo.github.io/QQMusicApi/#/?id=qqmusicapi)，当然，也可以直接用我部署好的接口地址（保证最近1年内是可用的，且修改过这个项目的后段代码）。

**Comment by earthaYan** [comment]
qq音乐有开发者文档，不可以直接用那个吗？
